### ISSUE TITLE
Build logic for card types into wordpress

### ISSUE THREAD

**Issue by annielcook** [ydntech/YDNRedesign#1]

**Comment by chrisxwan** [comment]
@floodfish For whatever reason, the switch to Small / Medium / Large / X-Large is not working. It's in the backend UI, but in the backend, I still have to use "featured" to get story-major. Any ideas on why?

**Comment by floodfish** [comment]
@chrisxwan It seems to be working for me. Maybe you had something cached or some of the old value names in your local database?

It looks to me like "large" is working to get a featured story, unless I'm misunderstanding the problem?

When looking at it, I just tweaked this and pushed: "standardized 'x-large' and 'X-large' to 'xlarge' in functions.php and index.php"
