### ISSUE TITLE
Social buttons on article page

### ISSUE THREAD

**Issue by annielcook** [ydntech/YDNRedesign#13]

**Comment by chrisxwan** [comment]
Jason had adblock on

**Comment by chrisxwan** [comment]
haha jk

**Comment by chrisxwan** [comment]
@aaronzlewis i am so behind when it comes to linkedin -- what are users expecting to see when they click the linkedin social media button? where should it take them?

**Comment by aaronzlewis** [comment]
@chrisxwan, sorry that is supposed to be an email button. I changed it locally, but forgot to push. Will do that tomorrow.



—

**Comment by chrisxwan** [comment]
@aaronzlewis no problem! i know you pushed it already, but when i load the article page, i dont see any email button. maybe you didn't add the image? not sure, could you push it again?

**Comment by annielcook** [comment]
@chrisxwan  linkedin still isnt working

**Comment by chrisxwan** [comment]
Yeah it's an easy fix but I don't think it's supposed to be linkedin

**Comment by aaronzlewis** [comment]
It should work now


—

**Comment by annielcook** [comment]
@chrisxwan are we doing linkedin on the side bar and email on the bottom bar?

**Comment by chrisxwan** [comment]
Uhhh I’ll work on whatever Aaron put in static, which is email on sidebar and no linked, I think.


—

**Comment by chrisxwan** [comment]
pretty sure this is done
