### ISSUE TITLE
Figure out multiple featured images

### ISSUE THREAD

**Issue by floodfish** [ydntech/YDNRedesign#16]
So that we can have our 2:1 and our 1:1. It seems to be a thing:
https://wordpress.org/support/topic/multiple-featured-image-sizes
https://wordpress.org/support/topic/different-featured-image-sizes-depending-on-page
http://www.wpbeginner.com/plugins/how-to-add-multiple-post-thumbnails-featured-images-in-wordpress/

**Comment by annielcook** [comment]
@floodfish this is the plugin im planning on using -- any thoughts? 

https://wordpress.org/plugins/multiple-post-thumbnails/

**Comment by floodfish** [comment]
@annielcook yeah, do it!
