### ISSUE TITLE
Category page -- looks craaaazy 

### ISSUE THREAD

**Issue by annielcook** [ydntech/YDNRedesign#20]

**Comment by chrisxwan** [comment]
@lawrencealexander10 aren't you working on this?

**Comment by lawrencealexander10** [comment]
@chrisxwan sorry i didn't realize it was assigned.I havent designed the category cards etc

**Comment by chrisxwan** [comment]
Other than that, what else needs to be done for this?

**Comment by annielcook** [comment]
still needs category box
