### ISSUE TITLE
bottom bar cut off on 480px

### ISSUE THREAD

**Issue by lawrencealexander10** [ydntech/YDNRedesign#48]

**Comment by annielcook** [comment]
@lawrencealexander10 what does this mean

**Comment by lawrencealexander10** [comment]
When you make the screen 480px the bottom bar is there but you can't see any of the words. The plan is to just remove it before we hit this issue

Cheers,
Alex

**Comment by annielcook** [comment]
@lawrencealexander10 is this finished?

**Comment by lawrencealexander10** [comment]
Yup
