### ISSUE TITLE
Make stylesheets CASCADING 

### ISSUE THREAD

**Issue by chrisxwan** [ydntech/YDNRedesign#53]

**Comment by chrisxwan** [comment]
@annielcook @floodfish @lawrencealexander10 

Working on this at the moment and it's actually really difficult because our original static mockup was done entirely so that the classes don't stack on each other. As an example, compare story-majors from static to docroot. Also, try shrinking our current site down to mobile and look at story-major. It's messed up mainly because of the stacked classes. I tried cascading the SCSS, and there are still further complications. Are we sure we wanna' cascade this / stack classes? If so, could I grab one of you to help me with it? I can't do it alone. If we don't wanna' cascade it / stack classes, I'm absolutely sure I can account for this in the card logic. Please let me know.

**Comment by floodfish** [comment]
What is this ticket referring too, exactly? I remember the words coming up in our meeting, but I can't recall what part of the styles it was about.

Also, I don't understand what "stacked" means here, @chrisxwan ... Do you mean that a card has multiple classes?  Do you mean nested SCSS?

**Comment by chrisxwan** [comment]
In static, a card that is 2x2 will have the class story-major but NOT story-preview or story-photo. For the actual site, do we want to stack these classes on top of each other such that a 2x2 card will have story-major, story-preview, AND story-photo? If I remember correctly, we did want to do this, and one thing that was suggested was to simply make the stylesheets cascade in order of priority.

—
