### ISSUE TITLE
Add add boxes to show biz team

### ISSUE THREAD

**Issue by annielcook** [ydntech/YDNRedesign#57]

**Comment by annielcook** [comment]
@floodfish what should the the two banner ads do for small screens?

![screen shot 2015-07-12 at 2 30 47 pm](https://cloud.githubusercontent.com/assets/6455793/8639278/a36bcc2c-28a2-11e5-8146-7c1dfbce5b76.png)


Would we have to get the biz team to upload multiple aspect ratios for each if we made them responsive?

**Comment by floodfish** [comment]
This is a good question for all ad units, not just the two banners. If the biz team and or their software can accommodate responsive units, that would be ideal. 

(As an aside, this is a good example of the kind of thing we would likely have noticed sooner if we designed mobile-first)
